# Generated by Django 2.2.2 on 2020-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
